/**
 * Cross-language contract parity tests.
 *
 * The Rust engine (`cognis-cli`, the `indexd` surface) emits JSON that this
 * extension parses into the interfaces in `types.ts` and normalizes in
 * `indexd.ts` / `mcpConfig.ts`. Those JSON shapes are a contract across two
 * languages; if the Rust side drops or renames a field, the extension breaks
 * silently.
 *
 * The E2E suite captures the *real* CLI/daemon output into golden skeleton
 * files under `tests/e2e/contracts/` (key names + value types, with
 * environment-specific values stripped). These tests load those same goldens
 * and assert every field the extension actually reads is present in the
 * contract — so a drift on the Rust side fails here, and a drift on the
 * TypeScript side (reading a field the contract doesn't promise) fails too.
 *
 * If a contract change is intentional: regenerate the goldens, then update the
 * matching interface in `types.ts` and the expected key list below.
 */
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";
import test from "node:test";

// Resolve tests/e2e/contracts relative to this compiled test file. From
// apps/cognis-vscode/out/test/ the repo root is four levels up.
const CONTRACTS_DIR = path.resolve(
  __dirname,
  "..",
  "..",
  "..",
  "..",
  "tests",
  "e2e",
  "contracts"
);

/**
 * Load a committed contract golden, or return `undefined` when it is not
 * present. The golden files live at the repo root and are generated by the
 * Python `e2e` suite; the standalone VS Code extension CI job checks out the
 * same repo, so they are normally present. We skip (rather than fail) when they
 * are absent so this node-only job stays self-contained — the Python `e2e` job
 * is the authoritative gate that the goldens exist and match real output.
 */
function loadContract(name: string): Record<string, unknown> | undefined {
  const file = path.join(CONTRACTS_DIR, name);
  if (!fs.existsSync(file)) {
    return undefined;
  }
  return JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, unknown>;
}

/** Assert every key in `required` is present in `contract`. */
function assertKeys(
  contract: Record<string, unknown>,
  required: string[],
  label: string
): void {
  for (const key of required) {
    assert.ok(
      key in contract,
      `${label}: contract is missing field '${key}' the extension reads. ` +
        `The Python output shape drifted from types.ts.`
    );
  }
}

test("WorkspacePaths interface matches the real `cognis-cli paths` contract", (t) => {
  const contract = loadContract("paths.json");
  if (!contract) {
    t.skip("contract golden paths.json not present (generated by the Python e2e suite)");
    return;
  }
  // Fields read in workspace.ts / indexd.ts via the WorkspacePaths type.
  assertKeys(
    contract,
    [
      "repo_root",
      "cognis_dir",
      "config_path",
      "db_path",
      "indexd_status_path",
      "audit_log_path",
      "capsule_cache_dir",
      "golden_set_path",
      "runtime_version",
      "engine_binary",
    ],
    "WorkspacePaths"
  );
});

test("McpConfigPayload interface matches the real `cognis-cli mcp-config` contract", (t) => {
  const contract = loadContract("mcp_config.json");
  if (!contract) {
    t.skip("contract golden mcp_config.json not present (generated by the Python e2e suite)");
    return;
  }
  // Fields read in mcpConfig.ts via the McpConfigPayload type.
  assertKeys(
    contract,
    ["host", "format", "repo_root", "server_name", "config", "config_paths", "env"],
    "McpConfigPayload"
  );
  const config = contract.config as Record<string, unknown>;
  assert.ok("mcpServers" in config, "McpConfigPayload.config must carry mcpServers");
  const servers = config.mcpServers as Record<string, Record<string, unknown>>;
  const firstServer = Object.values(servers)[0];
  assert.ok(firstServer, "expected at least one server block in the contract");
  // McpServerBlock: command + env are required; args is optional.
  assertKeys(firstServer, ["command", "env"], "McpServerBlock");
  const env = firstServer.env as Record<string, unknown>;
  assert.ok(
    "COGNIS_DB_PATH" in env,
    "MCP server env must carry COGNIS_DB_PATH (envMatchesRepo depends on it)"
  );
});

test("HealthReport interface matches the real `cognis-cli health` contract", (t) => {
  const contract = loadContract("health.json");
  if (!contract) {
    t.skip("contract golden health.json not present (generated by the Python e2e suite)");
    return;
  }
  assertKeys(contract, ["runtime_version", "overall", "checks"], "HealthReport");
  const checks = contract.checks as Record<string, Record<string, unknown>>;
  const sample = Object.values(checks)[0];
  assert.ok(sample, "expected a sample health check in the contract");
  assertKeys(sample, ["status", "message"], "HealthReport.checks[*]");
});

test("BootstrapPayload interface matches the real `cognis-cli bootstrap` contract", (t) => {
  const contract = loadContract("bootstrap.json");
  if (!contract) {
    t.skip("contract golden bootstrap.json not present (generated by the Python e2e suite)");
    return;
  }
  const keys = contract.keys as string[];
  // Fields read in workspace.ts / extension.ts via the BootstrapPayload type.
  for (const required of [
    "command",
    "runtime_version",
    "repo_root",
    "db_path",
    "skip_embeddings",
    "paths",
    "phases",
    "health",
    "overall",
    "exit_code",
  ]) {
    assert.ok(
      keys.includes(required),
      `BootstrapPayload: contract missing top-level field '${required}'`
    );
  }
});

test("IndexStatusReport normalizer matches the real indexd status-file contract", (t) => {
  const contract = loadContract("indexd_status.json");
  if (!contract) {
    t.skip("contract golden indexd_status.json not present (generated by the Python e2e suite)");
    return;
  }
  // snake_case keys read by normalizeIndexStatus() in indexd.ts.
  assertKeys(
    contract,
    [
      "pid",
      "active",
      "phase",
      "message",
      "progress_percent",
      "pending_count",
      "pending_files",
      "inflight_count",
      "inflight_files",
      "recent_files",
      "updated_at",
      "last_error",
    ],
    "IndexStatusReport (status file)"
  );
});
