-- cognis migration 001 — initial UCKG schema (MVP, Phase 1).
--
-- Mirrors design.md "Data Models" verbatim for the MVP tables only:
--   symbol, edge, symbol_attribute, file, symbol_fts, symbol_vec, meta.
-- Phase 2+ tables (commit_log, commit_touch, pr, ownership, runtime_signal,
-- session, session_event) are stubbed as commented-out blocks at the bottom of
-- this file so future migrations have a known shape to extend from.
--
-- IMPORTANT (rust-engine-migration spec, Requirement 2): this file is an exact,
-- verbatim copy of packages/core/cognis/migrations/001_initial.sql. The UCKG
-- schema is immutable — table/column/index names, WAL mode, the
-- `meta.dst_missing` convention, and the `node_id` format must stay identical so
-- a `.cognis/uckg.db` created by the Python engine opens unchanged in Rust.
-- Do NOT edit this file to change the schema; ship a new numbered migration.
--
-- Notes:
--  * sqlite-vec's `vec0` virtual table is created at runtime by the store
--    after the extension is loaded successfully. The fallback table here
--    (`symbol_vec`) holds the same shape (id PK + embedding BLOB) so the rest
--    of the indexer can still write rows when the extension isn't available.
--    The runtime drops + recreates as `vec0(...)` when the extension loads.
--  * `symbol_fts` is a contentless FTS5 table mirrored to `symbol`. The
--    indexer is responsible for keeping rows in sync (no triggers — design
--    Indexer Pipeline → Writer keeps the writer single-threaded and explicit).

-- ---------------------------------------------------------------------------
-- meta — schema/runtime version key/value store (design "Resolved Open Questions").
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- symbol — atomic indexable unit (function, class, route, ...).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS symbol (
  id               TEXT PRIMARY KEY,
  kind             TEXT NOT NULL,
  name             TEXT NOT NULL,
  qualified_name   TEXT NOT NULL,
  language         TEXT NOT NULL,
  module           TEXT NOT NULL,
  file_path        TEXT NOT NULL,
  line_start       INTEGER NOT NULL,
  line_end         INTEGER NOT NULL,
  signature        TEXT,
  docstring        TEXT,
  content_hash     TEXT NOT NULL,
  body_excerpt     TEXT,
  semantic_summary TEXT,
  risk_score       REAL NOT NULL DEFAULT 0.0,
  ambiguous        INTEGER NOT NULL DEFAULT 0,
  untrusted_flags  TEXT,
  updated_at       INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_symbol_file   ON symbol(file_path);
CREATE INDEX IF NOT EXISTS idx_symbol_module ON symbol(module);
CREATE INDEX IF NOT EXISTS idx_symbol_qname  ON symbol(qualified_name);
CREATE INDEX IF NOT EXISTS idx_symbol_kind   ON symbol(kind);

-- ---------------------------------------------------------------------------
-- edge — directed, typed relationship between two symbols.
--
-- Why no FK on (src_id, dst_id) → symbol(id):
-- CP-3 requires that on `delete_symbol(x)` the inbound edges `(*, x, *)` are
-- kept (and flagged `meta.dst_missing=true`) for archaeology. A strict FK
-- with `ON DELETE NO ACTION` would block that delete; `CASCADE` would erase
-- the audit trail. SQLite has no "dangle allowed" mode, so the FK is enforced
-- at the application layer in cognis.db.delete_symbol instead. Composite PK
-- + the (src,dst) indexes still give us referential reads in O(log n).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS edge (
  src_id      TEXT NOT NULL,
  dst_id      TEXT NOT NULL,
  kind        TEXT NOT NULL,
  confidence  REAL NOT NULL DEFAULT 1.0,
  meta        TEXT,
  PRIMARY KEY (src_id, dst_id, kind)
);
CREATE INDEX IF NOT EXISTS idx_edge_src ON edge(src_id, kind);
CREATE INDEX IF NOT EXISTS idx_edge_dst ON edge(dst_id, kind);

-- ---------------------------------------------------------------------------
-- symbol_attribute — side-effect / contract metadata (db_table, http_route, ...).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS symbol_attribute (
  symbol_id TEXT NOT NULL,
  key       TEXT NOT NULL,
  value     TEXT NOT NULL,
  PRIMARY KEY (symbol_id, key, value),
  FOREIGN KEY (symbol_id) REFERENCES symbol(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- file — per-file cache for the incremental watcher.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS file (
  path         TEXT PRIMARY KEY,
  language     TEXT NOT NULL,
  size_bytes   INTEGER NOT NULL,
  content_hash TEXT NOT NULL,
  parsed_at    INTEGER NOT NULL,
  parse_status TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- symbol_fts — FTS5 over the symbol surface text.
-- Contentless: rows are populated explicitly by the indexer Writer.
-- ---------------------------------------------------------------------------
CREATE VIRTUAL TABLE IF NOT EXISTS symbol_fts USING fts5(
  id UNINDEXED,
  name,
  qualified_name,
  signature,
  docstring,
  body_excerpt,
  tokenize = 'unicode61 remove_diacritics 2'
);

-- ---------------------------------------------------------------------------
-- symbol_vec — fallback embedding store.
-- Replaced at runtime by `CREATE VIRTUAL TABLE symbol_vec USING vec0(...)`
-- when sqlite-vec is loaded. See cognis.db._ensure_vec_table.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS symbol_vec (
  symbol_id TEXT PRIMARY KEY,
  embedding BLOB NOT NULL,
  FOREIGN KEY (symbol_id) REFERENCES symbol(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Phase 2+ tables (deferred; commented out until their owning migration ships).
-- Kept here as DDL skeletons so `tasks-phase2.md` migrations have a starting
-- point. Do *not* CREATE these in 001 — adding columns later is cheaper than
-- removing them.
-- ---------------------------------------------------------------------------
--
-- CREATE TABLE commit_log (
--   sha          TEXT PRIMARY KEY,
--   author       TEXT NOT NULL,
--   authored_at  INTEGER NOT NULL,
--   message      TEXT NOT NULL,
--   pr_id        TEXT
-- );
--
-- CREATE TABLE commit_touch (
--   sha        TEXT NOT NULL,
--   symbol_id  TEXT NOT NULL,
--   change     TEXT NOT NULL,
--   PRIMARY KEY (sha, symbol_id)
-- );
--
-- CREATE TABLE pr (
--   id           TEXT PRIMARY KEY,
--   title        TEXT NOT NULL,
--   body         TEXT,
--   state        TEXT NOT NULL,
--   merged_at    INTEGER,
--   base_sha     TEXT,
--   head_sha     TEXT
-- );
--
-- CREATE TABLE ownership (
--   symbol_id     TEXT NOT NULL,
--   email         TEXT NOT NULL,
--   blame_lines   INTEGER NOT NULL,
--   last_touched  INTEGER NOT NULL,
--   PRIMARY KEY (symbol_id, email)
-- );
--
-- CREATE TABLE runtime_signal (
--   id           TEXT PRIMARY KEY,
--   symbol_id    TEXT NOT NULL,
--   source       TEXT NOT NULL,
--   kind         TEXT NOT NULL,
--   observed_at  INTEGER NOT NULL,
--   payload      TEXT NOT NULL
-- );
--
-- CREATE TABLE session (
--   id          TEXT PRIMARY KEY,
--   client      TEXT NOT NULL,
--   started_at  INTEGER NOT NULL,
--   ended_at    INTEGER
-- );
--
-- CREATE TABLE session_event (
--   session_id  TEXT NOT NULL,
--   seq         INTEGER NOT NULL,
--   kind        TEXT NOT NULL,
--   payload     TEXT NOT NULL,
--   ts          INTEGER NOT NULL,
--   PRIMARY KEY (session_id, seq)
-- );
